import { useEffect, useMemo, useState } from 'react'
import { BarChart3, Boxes, History, PackagePlus, Search, ShoppingCart, Trash2, X } from 'lucide-react'

type Category = 'Bebidas' | 'Comidas' | 'Doses' | 'Tabacaria' | 'Outros'
type Payment = 'Pix' | 'Dinheiro' | 'Débito' | 'Crédito'
type Product = { id:number; name:string; category:Category; price:number; stock:number; barcode?:string; active:boolean; trackStock?:boolean }
type CartItem = { productId:number; qty:number }
type Sale = { id:number; createdAt:string; payment:Payment; total:number; received?:number; change?:number; items:Array<{productId:number;name:string;qty:number;price:number;trackStock?:boolean}> }
type Tab = 'vender'|'historico'|'estoque'|'produtos'|'resumo'

const initialProducts: Product[] = [
{id:1,name:'Coca-Cola Lata',category:'Bebidas',price:6,stock:24,barcode:'7894900011517',active:true},{id:2,name:'Coca-Cola 2L',category:'Bebidas',price:12,stock:10,barcode:'7894900027013',active:true},{id:3,name:'Guaraná Lata',category:'Bebidas',price:5,stock:18,active:true},{id:4,name:'Água 500ml',category:'Bebidas',price:4,stock:30,active:true},{id:5,name:'Del Valle Uva',category:'Bebidas',price:6,stock:12,active:true},{id:6,name:'Del Valle Pêssego',category:'Bebidas',price:6,stock:10,active:true},{id:7,name:'Energético',category:'Bebidas',price:12,stock:14,active:true},{id:8,name:'Água com Gás',category:'Bebidas',price:5,stock:16,active:true},{id:9,name:'Jantinha Completa',category:'Comidas',price:18,stock:0,active:true,trackStock:false},{id:10,name:'Espetinho Carne',category:'Comidas',price:10,stock:0,active:true,trackStock:false},{id:11,name:'Espetinho Frango',category:'Comidas',price:9,stock:0,active:true,trackStock:false},{id:12,name:'Porção de Batata',category:'Comidas',price:20,stock:0,active:true,trackStock:false},{id:13,name:'Salgado',category:'Comidas',price:7,stock:15,active:true},{id:14,name:'Dose Cachaça',category:'Doses',price:5,stock:0,active:true,trackStock:false},{id:15,name:'Dose Whisky',category:'Doses',price:12,stock:0,active:true,trackStock:false},{id:16,name:'Dose Vodka',category:'Doses',price:9,stock:0,active:true,trackStock:false},{id:17,name:'Dose Campari',category:'Doses',price:10,stock:0,active:true,trackStock:false},{id:18,name:'Palheiro Tradicional',category:'Tabacaria',price:3,stock:50,active:true},{id:19,name:'Palheiro Menta',category:'Tabacaria',price:3.5,stock:35,active:true},{id:20,name:'Isqueiro',category:'Tabacaria',price:6,stock:20,active:true},{id:21,name:'Chiclete',category:'Outros',price:2,stock:40,active:true},{id:22,name:'Paçoca',category:'Outros',price:2.5,stock:25,active:true},{id:23,name:'Gelo 3kg',category:'Outros',price:10,stock:8,active:true},{id:24,name:'Carvão 3kg',category:'Outros',price:18,stock:7,active:true},{id:25,name:'Copo Descartável',category:'Outros',price:1,stock:100,active:true}]
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v)
const tracked=(p:Product)=>p.trackStock!==false

export default function App(){
 const [products,setProducts]=useState<Product[]>(()=>JSON.parse(localStorage.getItem('bdc_products')||'null')||initialProducts)
 const [sales,setSales]=useState<Sale[]>(()=>JSON.parse(localStorage.getItem('bdc_sales')||'[]'))
 const [cart,setCart]=useState<CartItem[]>([]),[tab,setTab]=useState<Tab>('vender'),[query,setQuery]=useState(''),[category,setCategory]=useState('Todos')
 const [paymentOpen,setPaymentOpen]=useState(false),[cashOpen,setCashOpen]=useState(false),[received,setReceived]=useState(''),[newProductOpen,setNewProductOpen]=useState(false)
 useEffect(()=>localStorage.setItem('bdc_products',JSON.stringify(products)),[products]); useEffect(()=>localStorage.setItem('bdc_sales',JSON.stringify(sales)),[sales])
 const filtered=useMemo(()=>products.filter(p=>p.active&&(category==='Todos'||p.category===category)&&(!query||p.name.toLowerCase().includes(query.toLowerCase())||p.barcode?.includes(query))),[products,category,query])
 const cartDetails=cart.map(i=>({...i,product:products.find(p=>p.id===i.productId)!})).filter(i=>i.product), total=cartDetails.reduce((s,i)=>s+i.product.price*i.qty,0)
 const addToCart=(p:Product)=>{if(tracked(p)&&p.stock<=0)return;setCart(prev=>{const f=prev.find(i=>i.productId===p.id),q=f?.qty||0;if(tracked(p)&&q>=p.stock)return prev;return f?prev.map(i=>i.productId===p.id?{...i,qty:i.qty+1}:i):[...prev,{productId:p.id,qty:1}]})}
 const updateQty=(id:number,d:number)=>{const p=products.find(x=>x.id===id);if(!p)return;setCart(prev=>prev.map(i=>i.productId===id?{...i,qty:Math.max(0,tracked(p)?Math.min(p.stock,i.qty+d):i.qty+d)}:i).filter(i=>i.qty>0))}
 const scan=(e:React.KeyboardEvent<HTMLInputElement>)=>{if(e.key!=='Enter')return;const code=query.trim();const p=products.find(x=>x.active&&x.barcode===code);if(p){e.preventDefault();addToCart(p);setQuery('')}}
 const finishSale=(payment:Payment,cash?:number)=>{if(!cart.length)return;const sale:Sale={id:(sales[0]?.id||0)+1,createdAt:new Date().toISOString(),payment,total,received:cash,change:cash!==undefined?cash-total:undefined,items:cartDetails.map(i=>({productId:i.product.id,name:i.product.name,qty:i.qty,price:i.product.price,trackStock:i.product.trackStock}))};setSales(p=>[sale,...p]);setProducts(prev=>prev.map(p=>{const i=cart.find(x=>x.productId===p.id);return i&&tracked(p)?{...p,stock:Math.max(0,p.stock-i.qty)}:p}));setCart([]);setPaymentOpen(false);setCashOpen(false);setReceived('')}
 const choosePayment=(p:Payment)=>{if(p==='Dinheiro'){setPaymentOpen(false);setCashOpen(true)}else finishSale(p)}
 const cancelSale=(s:Sale)=>{if(!confirm(`Cancelar a venda #${String(s.id).padStart(4,'0')}?`))return;setProducts(prev=>prev.map(p=>{const i=s.items.find(x=>x.productId===p.id);return i&&i.trackStock!==false&&tracked(p)?{...p,stock:p.stock+i.qty}:p}));setSales(prev=>prev.filter(x=>x.id!==s.id))}
 const today=new Date().toDateString(),todaySales=sales.filter(s=>new Date(s.createdAt).toDateString()===today),todayRevenue=todaySales.reduce((a,b)=>a+b.total,0)
 const paymentTotals=(['Pix','Dinheiro','Débito','Crédito'] as Payment[]).map(p=>({label:p,value:todaySales.filter(s=>s.payment===p).reduce((a,b)=>a+b.total,0)}))
 const topProducts=useMemo(()=>{const m=new Map<string,number>();todaySales.flatMap(s=>s.items).forEach(i=>m.set(i.name,(m.get(i.name)||0)+i.qty));return[...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5)},[todaySales])
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span>BC</span><div><strong>Bar do Ceará</strong><small>PDV local</small></div></div><nav><Nav icon={<ShoppingCart size={20}/>} label="Vender" active={tab==='vender'} onClick={()=>setTab('vender')}/><Nav icon={<History size={20}/>} label="Histórico" active={tab==='historico'} onClick={()=>setTab('historico')}/><Nav icon={<Boxes size={20}/>} label="Estoque" active={tab==='estoque'} onClick={()=>setTab('estoque')}/><Nav icon={<PackagePlus size={20}/>} label="Produtos" active={tab==='produtos'} onClick={()=>setTab('produtos')}/><Nav icon={<BarChart3 size={20}/>} label="Resumo" active={tab==='resumo'} onClick={()=>setTab('resumo')}/></nav><div className="sidebar-status"><span/>Funcionando offline</div></aside>
 <main className="main">{tab==='vender'&&<><header className="page-header"><div><h1>Nova venda</h1><p>Escolha os produtos e feche a venda em poucos cliques.</p></div><div className="date-chip">{new Date().toLocaleDateString('pt-BR')}</div></header><div className="sell-layout"><section className="products-panel"><div className="search-row"><div className="search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={scan} placeholder="Buscar produto ou escanear código de barras" autoFocus/></div></div><div className="categories">{['Todos','Bebidas','Comidas','Doses','Tabacaria','Outros'].map(c=><button className={category===c?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><div className="product-grid">{filtered.map(p=><button className={`product-card ${tracked(p)&&p.stock<=3?'low':''}`} key={p.id} onClick={()=>addToCart(p)}><span className="product-category">{p.category}</span><strong>{p.name}</strong><b>{money(p.price)}</b><small>{!tracked(p)?'Venda livre':p.stock>0?`${p.stock} em estoque`:'Sem estoque'}</small></button>)}</div></section><aside className="cart-panel"><div className="cart-title"><div><ShoppingCart size={21}/><strong>Carrinho</strong></div><span>{cart.reduce((a,b)=>a+b.qty,0)} itens</span></div><div className="cart-items">{!cartDetails.length?<div className="empty"><ShoppingCart size={38}/><p>Seu carrinho está vazio</p><small>Clique em um produto para adicionar.</small></div>:cartDetails.map(i=><div className="cart-item" key={i.productId}><div className="cart-item-name"><strong>{i.product.name}</strong><small>{money(i.product.price)} cada</small></div><div className="qty"><button onClick={()=>updateQty(i.productId,-1)}>−</button><span>{i.qty}</span><button onClick={()=>updateQty(i.productId,1)}>+</button></div><b>{money(i.product.price*i.qty)}</b></div>)}</div><div className="cart-footer"><div className="total"><span>Total</span><strong>{money(total)}</strong></div><button className="primary" disabled={!cart.length} onClick={()=>setPaymentOpen(true)}>Finalizar venda</button></div></aside></div></>}
 {tab==='historico'&&<Section title="Histórico de vendas" subtitle="Todas as vendas registradas neste navegador."><div className="table-card"><table><thead><tr><th>Venda</th><th>Data e hora</th><th>Pagamento</th><th>Itens</th><th>Total</th><th></th></tr></thead><tbody>{sales.map(s=><tr key={s.id}><td>#{String(s.id).padStart(4,'0')}</td><td>{new Date(s.createdAt).toLocaleString('pt-BR')}</td><td><span className="pill">{s.payment}</span>{s.change!==undefined&&<small style={{display:'block',marginTop:4}}>Troco {money(s.change)}</small>}</td><td>{s.items.reduce((a,b)=>a+b.qty,0)}</td><td><strong>{money(s.total)}</strong></td><td><button className="danger-link" onClick={()=>cancelSale(s)}>Cancelar</button></td></tr>)}</tbody></table>{!sales.length&&<div className="empty-table">Nenhuma venda registrada ainda.</div>}</div></Section>}
 {tab==='estoque'&&<Section title="Estoque" subtitle="Controle só o que realmente precisa ser contado."><div className="table-card"><table><thead><tr><th>Produto</th><th>Categoria</th><th>Estoque</th><th>Preço</th><th>Código</th><th>Ajuste rápido</th></tr></thead><tbody>{products.filter(p=>p.active).map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td>{p.category}</td><td>{tracked(p)?<span className={`stock-badge ${p.stock<=3?'critical':p.stock<=8?'warning':''}`}>{p.stock}</span>:<span className="pill">Venda livre</span>}</td><td>{money(p.price)}</td><td>{p.barcode||'Manual'}</td><td>{tracked(p)?<div className="adjust"><button onClick={()=>setProducts(x=>x.map(v=>v.id===p.id?{...v,stock:Math.max(0,v.stock-1)}:v))}>−1</button><button onClick={()=>setProducts(x=>x.map(v=>v.id===p.id?{...v,stock:v.stock+1}:v))}>+1</button><button onClick={()=>setProducts(x=>x.map(v=>v.id===p.id?{...v,stock:v.stock+12}:v))}>+12</button></div>:<span className="muted">Sem baixa</span>}</td></tr>)}</tbody></table></div></Section>}
 {tab==='produtos'&&<Section title="Produtos" subtitle="Cadastre qualquer item, com ou sem código de barras." action={<button className="primary small" onClick={()=>setNewProductOpen(true)}>+ Novo produto</button>}><div className="table-card"><table><thead><tr><th>Produto</th><th>Categoria</th><th>Preço</th><th>Estoque</th><th>Código</th><th>Status</th><th></th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td>{p.category}</td><td>{money(p.price)}</td><td>{tracked(p)?p.stock:'Livre'}</td><td>{p.barcode||'Manual'}</td><td>{p.active?'Ativo':'Inativo'}</td><td><button className="icon-danger" onClick={()=>{const used=sales.some(s=>s.items.some(i=>i.productId===p.id));if(used)setProducts(x=>x.map(v=>v.id===p.id?{...v,active:false}:v));else setProducts(x=>x.filter(v=>v.id!==p.id))}}><Trash2 size={17}/></button></td></tr>)}</tbody></table></div></Section>}
 {tab==='resumo'&&<Section title="Resumo do dia" subtitle="O que entrou hoje, sem depender da memória de ninguém."><div className="metrics"><Metric label="Faturamento" value={money(todayRevenue)}/><Metric label="Vendas" value={String(todaySales.length)}/><Metric label="Ticket médio" value={money(todaySales.length?todayRevenue/todaySales.length:0)}/><Metric label="Itens vendidos" value={String(todaySales.flatMap(s=>s.items).reduce((a,b)=>a+b.qty,0))}/></div><div className="dashboard-grid"><div className="panel"><h3>Por forma de pagamento</h3>{paymentTotals.map(p=><div className="pay-line" key={p.label}><span>{p.label}</span><strong>{money(p.value)}</strong></div>)}</div><div className="panel"><h3>Mais vendidos hoje</h3>{topProducts.length?topProducts.map(([n,q],i)=><div className="rank" key={n}><span>{i+1}</span><p>{n}</p><strong>{q}</strong></div>):<p className="muted">Ainda não houve vendas hoje.</p>}</div></div></Section>}</main>
 {paymentOpen&&<div className="modal-backdrop"><div className="modal"><button className="modal-x" onClick={()=>setPaymentOpen(false)}><X/></button><h2>Forma de pagamento</h2><p>Total da venda: <strong>{money(total)}</strong></p><div className="payment-grid">{(['Pix','Dinheiro','Débito','Crédito'] as Payment[]).map(p=><button key={p} onClick={()=>choosePayment(p)}>{p}</button>)}</div></div></div>}
 {cashOpen&&<div className="modal-backdrop"><form className="modal product-modal" onSubmit={e=>{e.preventDefault();const n=Number(received.replace(',','.'));if(n>=total)finishSale('Dinheiro',n)}}><button type="button" className="modal-x" onClick={()=>setCashOpen(false)}><X/></button><h2>Pagamento em dinheiro</h2><p>Total: <strong>{money(total)}</strong></p><label>Valor recebido<input autoFocus value={received} onChange={e=>setReceived(e.target.value)} placeholder="Ex.: 50,00" inputMode="decimal"/></label><div className="total" style={{margin:'18px 0'}}><span>Troco</span><strong>{money(Math.max(0,(Number(received.replace(',','.'))||0)-total))}</strong></div><button className="primary" type="submit" disabled={(Number(received.replace(',','.'))||0)<total}>Confirmar venda</button></form></div>}
 {newProductOpen&&<ProductModal onClose={()=>setNewProductOpen(false)} onSave={p=>{setProducts(x=>[...x,{...p,id:Math.max(0,...x.map(v=>v.id))+1,active:true}]);setNewProductOpen(false)}}/>}</div>
}
function Nav({icon,label,active,onClick}:{icon:any,label:string,active:boolean,onClick:()=>void}){return <button className={active?'nav active':'nav'} onClick={onClick}>{icon}<span>{label}</span></button>}
function Section({title,subtitle,children,action}:{title:string,subtitle:string,children:any,action?:any}){return <><header className="page-header"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</header>{children}</>}
function Metric({label,value}:{label:string,value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function ProductModal({onClose,onSave}:{onClose:()=>void,onSave:(p:Omit<Product,'id'|'active'>)=>void}){const[name,setName]=useState(''),[price,setPrice]=useState(''),[stock,setStock]=useState(''),[barcode,setBarcode]=useState(''),[category,setCategory]=useState<Category>('Bebidas'),[trackStock,setTrackStock]=useState(true);return <div className="modal-backdrop"><form className="modal product-modal" onSubmit={e=>{e.preventDefault();if(!name||!price)return;onSave({name,price:Number(price.replace(',','.')),stock:trackStock?Number(stock)||0:0,barcode:barcode||undefined,category,trackStock})}}><button type="button" className="modal-x" onClick={onClose}><X/></button><h2>Novo produto</h2><p>O mínimo necessário para colocar algo à venda.</p><label>Nome<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Coca-Cola 2L" required/></label><div className="form-row"><label>Preço<input value={price} onChange={e=>setPrice(e.target.value)} placeholder="12,00" inputMode="decimal" required/></label>{trackStock&&<label>Estoque inicial<input value={stock} onChange={e=>setStock(e.target.value)} placeholder="12" inputMode="numeric"/></label>}</div><label>Categoria<select value={category} onChange={e=>setCategory(e.target.value as Category)}>{['Bebidas','Comidas','Doses','Tabacaria','Outros'].map(c=><option key={c}>{c}</option>)}</select></label><label>Código de barras <small>(opcional)</small><input value={barcode} onChange={e=>setBarcode(e.target.value)} placeholder="Digite ou escaneie"/></label><label style={{display:'flex',flexDirection:'row',gap:10,alignItems:'center',margin:'12px 0 20px'}}><input type="checkbox" checked={trackStock} onChange={e=>setTrackStock(e.target.checked)} style={{width:18,height:18}}/> Controlar estoque deste produto</label><button className="primary" type="submit">Salvar produto</button></form></div>}
